# Generated by Django 6.0.1 on 2026-01-20 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("shinedust", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "accounts",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "set",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "Genetic Apex"),
                            ("A1a", "Mythical Island"),
                            ("A2", "Space-Time Smackdown"),
                            ("A2a", "Triumphant Light"),
                            ("A2b", "Shining Revelry"),
                            ("A3", "Celestial Guardians"),
                            ("A3a", "Extradimensional Crisis"),
                            ("A3b", "Eevee Grove"),
                            ("A4", "Wisdom of Sea and Sky"),
                            ("A4a", "Secluded Springs"),
                            ("A4b", "Deluxe Pack Ex"),
                            ("B1", "Mega Rising"),
                            ("B1a", "Crimson Blaze"),
                            ("P-A", "Promo A"),
                            ("P-B", "Promo B"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=100, null=True)),
                ("image_path", models.TextField(blank=True, null=True)),
                (
                    "rarity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1D", "Common"),
                            ("2D", "Uncommon"),
                            ("3D", "Rare"),
                            ("4D", "Double Rare"),
                            ("1S", "Illustration Rare"),
                            ("2S", "Super / Special Rare"),
                            ("3S", "Immersive"),
                            ("CR", "Crown Rare"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cards",
                "indexes": [models.Index(fields=["name"], name="idx_cards_name")],
                "unique_together": {("code", "set")},
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "set",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A1", "Genetic Apex"),
                            ("A1a", "Mythical Island"),
                            ("A2", "Space-Time Smackdown"),
                            ("A2a", "Triumphant Light"),
                            ("A2b", "Shining Revelry"),
                            ("A3", "Celestial Guardians"),
                            ("A3a", "Extradimensional Crisis"),
                            ("A3b", "Eevee Grove"),
                            ("A4", "Wisdom of Sea and Sky"),
                            ("A4a", "Secluded Springs"),
                            ("A4b", "Deluxe Pack Ex"),
                            ("B1", "Mega Rising"),
                            ("B1a", "Crimson Blaze"),
                            ("P-A", "Promo A"),
                            ("P-B", "Promo B"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.account",
                    ),
                ),
            ],
            options={
                "db_table": "screenshots",
            },
        ),
        migrations.CreateModel(
            name="ScreenshotCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                ("confidence", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        db_column="card_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.card",
                    ),
                ),
                (
                    "screenshot",
                    models.ForeignKey(
                        db_column="screenshot_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="db.screenshot",
                    ),
                ),
            ],
            options={
                "db_table": "screenshot_cards",
            },
        ),
        migrations.AddIndex(
            model_name="screenshot",
            index=models.Index(fields=["name"], name="idx_screenshots_clean_file"),
        ),
        migrations.AddIndex(
            model_name="screenshot",
            index=models.Index(fields=["account"], name="idx_screenshots_account"),
        ),
        migrations.AddIndex(
            model_name="screenshot",
            index=models.Index(fields=["timestamp"], name="idx_screenshots_timestamp"),
        ),
        migrations.AddIndex(
            model_name="screenshot",
            index=models.Index(fields=["processed"], name="idx_screenshots_processed"),
        ),
        migrations.AddIndex(
            model_name="screenshotcard",
            index=models.Index(
                fields=["screenshot"], name="idx_screenshot_cards_screen_id"
            ),
        ),
        migrations.AddIndex(
            model_name="screenshotcard",
            index=models.Index(fields=["card"], name="idx_screenshot_cards_card_id"),
        ),
        migrations.AlterUniqueTogether(
            name="screenshotcard",
            unique_together={("screenshot", "card", "position")},
        ),
    ]
