# Generated by Django 6.0.1 on 2026-02-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0002_alter_card_set_alter_screenshot_set"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
